#! /bin/sh
export JAVA_HOME="/opt/java/jdk1.8.0_181"
 
startcmd='/opt/app/wso2am-2.1.0/bin/wso2server.sh start> /dev/null &'
restartcmd='/opt/app/wso2am-2.1.0/bin/wso2server.sh restart> /dev/null &'
stopcmd='/opt/app/wso2am-2.1.0/bin/wso2server.sh stop> /dev/null &'
 
case "$1" in
start)
   echo "Starting the WSO2 Server ..."
   su -c "${startcmd}" wso2
;;
restart)
   echo "Re-starting the WSO2 Server ..."
   su -c "${restartcmd}" wso2
;;
stop)
   echo "Stopping the WSO2 Server ..."
   su -c "${stopcmd}" wso2
;;
*)
   echo "Usage: $0 {start|stop|restart}"
exit 1
esac